#!/bin/sh /etc/rc.common

SCRIPT_NAME="HueEmulator3.py"
SCRIPT_PATH="/opt/hue-emulator"
SCRIPT_PARAMS=""
PID_FILE="/tmp/hue-emulator.pid"

START=98

start() {
  if [ -f "$PID_FILE" ] && kill -0 $(cat "$PID_FILE"); then
    echo "$SCRIPT_NAME already running"
    return 1
  fi
  sleep 5
  . /etc/profile > /dev/null
  cd $SCRIPT_PATH
  ./$SCRIPT_NAME $SCRIPT_PARAMS >/dev/null 2>&1 & echo $! > $PID_FILE
  echo "Started $SCRIPT_NAME."
}

stop() {
  if [ ! -f "$PID_FILE" ] && ! kill -0 $(cat "$PID_FILE"); then
    echo "$SCRIPT_NAME not running"
    return 1
  fi
  kill -2 $(cat $PID_FILE)
  rm -f "$PID_FILE"
  echo "Stopped $SCRIPT_NAME."
}

restart() {
  stop
  start
}
