#!/bin/sh /etc/rc.common

SCRIPT_NAME="HueEmulator3.py"
SCRIPT_PATH="/opt/hue-emulator"
LED_PATH="/sys/class/leds"


START=98

start() {
sleep 5
. /etc/profile
echo "Starting $SCRIPT_NAME"
nohup python3 $SCRIPT_PATH/$SCRIPT_NAME >/dev/null 2>&1 &
}


