"Bug Report":
  - '- \[x\] I confirm that this is a bug report'
"Feature Request":
  - '- \[x\] I confirm that this is a feature request'
"Help Request":
  - '- \[x\] I confirm that this is a help request'
