name: Feature Request
description: Submit a feature request
labels: ["Feature Request"]
body:
  - type: markdown
    id: intro
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request! The feature request will be reviewed by the maintainers and, if accepted, will be labeled as such.
  - type: dropdown
    id: existing-feature
    attributes:
      label: "Feature does not already exist?"
      description: "Please search to see if your feature request already exists"
      options:
        - "No, I did not search"
        - "I searched and did not find an existing feature request"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Summarize feature"
      description: "Please provide a detailed description of the feature you are requesting"
    validations:
      required: true