version: '3'
services:
  diyHue:
    image: diyhue/core:latest
    # This makes for more convienient naming, but only allows one instance of the image
    container_name: diyHue
    restart: unless-stopped

    environment:
      # Uncomment to enable debug mode 
      # DEBUG: true
      # IP and MAC are only needed for running diyHue in the bridge network
      IP: 192.168.1.2
      MAC: 12:34:56:78:90
    volumes:
      - /mnt/hue-emulator/export:/opt/hue-emulator/export
    ports:
      - '80:80'
      - '443:443'
      - '1900:1900/udp'
      - '2100:2100/udp'
      - '1982:1982/udp'
    # Alternatively, you can activate host mode by uncommenting the line below and removing all ports and the env vars above
    # network_mode: "host"
