name: PR Build Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Image
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docker image
        run: |
          docker build -t diyhue/core:ci -f ./.build/Dockerfile --build-arg TARGETPLATFORM=linux/amd64 .
      - name: Run docker image
        if: success()
        run: |
          docker run -d --name "diyhue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=b8:27:eb:d4:dc:11' -e 'IP=192.168.1.123' -e 'DECONZ=192.168.1.111' -e 'IP_RANGE=5,6' -e 'DEBUG=true' diyhue/core:ci
          sleep 15
          docker logs diyhue
      - name: Cleanup
        run: |
          docker kill diyhue
          docker rm diyhue
